apiVersion: batch/v1
kind: Job
metadata:
  name: transfer-pvc 
  namespace: pacman-sample 
spec:
  template:
    spec:
      containers:
      - name: snapshot-to-pvc
        image: registry.redhat.io/openshift4/ose-cli:latest
        command: ["/bin/bash","/mover/transfer.sh"]
        env:
        - name: DESTINATION
          value: mongo-pvc 
        - name: SIZE
          value: 8Gi
        - name: PVC_NAME
          value: mongo-storage
        volumeMounts:
        - name: transfer-volume
          mountPath: /mover
      serviceAccount: transfer
      volumes:
        - name: transfer-volume
          configMap:
            name: transfer
      restartPolicy: Never
  backoffLimit: 40
