apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-binding 
  namespace: pacman-sample 
subjects:
- kind: ServiceAccount
  name: transfer 
roleRef:
  kind: Role
  name: snapshot-changer
  apiGroup: rbac.authorization.k8s.io
